### ISSUE TITLE
Loading some user profile pages is extremely slow

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#792] opened 2023-10-01 22:01 UTC
**Description**  
If you go to a user profile page, it can take an extremely long time to load, if it even does.

**How to Reproduce**  
1. Go to a user's profile
2. Observe the extremely long load times

**Expected Behavior**  
I expect a quick load time.

**Screenshots**  
N/A

**Device & App Version:**  
 - Device: Pixel 6
 - OS: Android 14
 - Thunder v0.2.4

**Additional Context**  
None.

**Comment by K4LCIFER** [comment] 2023-10-02 03:22
A working theory that I currently have is that the time that it takes to load the user profile is a function of how many posts that user has made. For example bot@lemmit.online would have an enormous number of posts, but I cannot load that user's profile even in the browser version.

**Comment by micahmo** [comment] 2023-10-02 03:36
> A working theory that I currently have is that the time that it takes to load the user profile is a function of how many posts that user has made.

I think that's a good theory! To be honest, I've never had issues loading user profiles. But I just tried that bot account you suggested, and, wow, you are right. I gave up waiting because it was taking so long. 😆 I wonder if there's an issue with paging.

**Comment by K4LCIFER** [comment] 2023-10-05 21:19
Could this be a Lemmy server issue?

**Comment by CTalvio** [comment] 2023-10-28 23:53
I'm approaching 2k posts on my main account, and whether my profile loads at a given time seems to be up to a flip of a coin. I've not blamed Thunder for this, as the same issue exists in the webUI and other apps.

Hence this is almost definitely a Lemmy issue, not a client problem.

Most of the time though, my profile loads just fine, it's only sometimes that it seems to be a struggle. It may be that fetching large account profiles is simply a particularly heavy DB operation that still needs improvement on the server side.

**Comment by hjiangsu** [comment] 2023-11-24 20:54
I'll keep this on hold for now since its not clear if its a Thunder issue or a server issue. If there's a specific user or method of reproduction, we can take a closer look at it and see if there's anything on our end which is causing this issue to happen.

**Comment by CTalvio** [comment] 2023-11-24 22:30
At the very least it would be good if, when the profile page fails to load, it wouldn't result in the "you are browsing lemmy.ml anonomously" screen with no way of refreshing.

To trigger a refresh you have to either completely close the app, or switch to another account and then back.

**Comment by hjiangsu** [comment] 2024-05-31 03:17
Since there's been quite a few changes under-the-hood with regards to user profiles (not to be confused with the account page), I'll go ahead and close this. However, feel free to open up a new issue if this is still something that you're noticing!

As a side-note: I opened up bot@lemmit.online on v0.4.0 and have not noticed any significant delays.

**Closed by hjiangsu** 2024-05-31 03:17 UTC
Labels: bug, on-hold
