### ISSUE TITLE
Pre-Collapsed comments won’t load

### ISSUE THREAD

**Issue by weksa** [thunder-app/thunder#750] opened 2023-09-20 01:12 UTC
**Description**
Some child comments are hidden when opening a post. They say, "Load # more replies..." Tapping on it attempts to load, but nothing loads. I've cross-checked via my instance's website lemm.ee that those child comments are visible.

**How to Reproduce**  
1. Go to any post with a lot of comments.
2. Look for any parent comment that has hidden child comments.
3. Tap "Load # more replies..."
4. Thunder attempts to load replies unsuccessfully.

**Expected Behavior** 
The child comments should have populated upon tapping to load them.

**Screenshots**  
![IMG_1058](https://github.com/thunder-app/thunder/assets/26491690/a67ecc10-0199-4359-af49-68c17a3e5530)

**Device & App Version:**  
 - Device: [iPhone13mini]
 - OS: [iOS17]
 - Version [0.2.3+16]

**Additional Context**  
I've replicated the problem with posts and comments from lemmy.world, lemmy.ml, sh.itjust.works, beehaw.org, mander.xyz. Lastly, I browsed local posts on my instance lemm.ee and was also able to find child comments that won't load.

**Comment by micahmo** [comment] 2023-09-20 02:27
Hi @weksa, thanks for the report! We do find that Lemmy frequently has trouble returning deferred comments (I think there's a back-end bug that occurs when one comment in the chain is deleted). However, up till now, any issue we've seen is Thunder is also seen in the web UI.

I was hoping to reproduce your issue with the example you gave, but unfortunately those comments are no longer deferred. 😞

| ![image](https://github.com/thunder-app/thunder/assets/7417301/a7fae9e6-65e5-4bcb-9121-3c9628b04d8e) |
| - |

| ![image](https://github.com/thunder-app/thunder/assets/7417301/8c14b2c7-5710-4933-baa1-baad9577546b) |
| - |

If there's any chance you could find another example of this (seems like you're running into it a lot 😆) and also provide a link to the post/comment, that would be super helpful! Thanks!

**Comment by weksa** [comment] 2023-09-20 03:15
https://sh.itjust.works/post/5470289

Link to 1st parent comment with screenshot below:

https://lemmy.world/comment/3606280



Link to 2nd parent comment with screenshot below:
https://literature.cafe/comment/1375959

**Comment by micahmo** [comment] 2023-09-20 03:30
Hey @weksa, thanks for the quick response! I'm not sure if some screenshots were supposed to come through, but I don't see any. 😞

Either way, neither of the comments you linked seem to be deferred in Thunder.

| ![image](https://github.com/thunder-app/thunder/assets/7417301/c035ce95-65ca-42d7-9f39-9836e175eff9) |
| - |

| ![image](https://github.com/thunder-app/thunder/assets/7417301/f221a7b8-9608-4d84-ac0b-07fd99cc7475) |
| - |

And I am logging into the instances you specified in Thunder (lemmy.world and literature.cafe, respectively). Maybe you can give me some more pointers as to what I might be doing wrong!

Also, I suppose there's a chance something was fixed in this area in the latest prerelease, although I don't recall anything like that.

**Comment by hjiangsu** [comment] 2024-02-17 00:23
I'll close this issue since there hasn't been any response so far. However, if this occurs again, feel free to open a new issue!

**Closed by hjiangsu** 2024-02-17 00:23 UTC
Labels: bug, question
