### ISSUE TITLE
Opening a post with NSFW picture, then exiting it again flashes the picture

### ISSUE THREAD

**Issue by krestenlaust** [thunder-app/thunder#314] opened 2023-07-10 15:56 UTC
**Description**  
The sliding animation of the picture shows the uncensored image.

**Expected Behavior**
Leave the image blurred no matter, until pressed.

**Screenshots**  

**Device & App Version:**  
 - Device: OnePlus 6T
 - OS: Android 11
 - Version: v0.2.1-alpha.1+11

**Comment by ajsosa** [comment] 2023-07-11 19:54
I think the problem is that we have ImageFilter->Hero->ExtendedImage so the `Hero` widget sits in-between the filter and the actual image and during state change, the `ImagerFilter` can't do its thing.

Changing the hierarchy to Hero->ImageFilter->ExtendedImage seems to keep the image blurred during the transition but now the Hero animation is all buggy. Not sure why that is, needs more investigation.

**Comment by ajsosa** [comment] 2023-07-11 20:02
Actually it might be a performance issue with `ImageFilter` re-bluring/painting as it transitions. Maybe if it's a NSFW image, we don't include the Hero widget as a work around.

**Comment by krestenlaust** [comment] 2023-07-11 20:19
> Maybe if it's a NSFW image, we don't include the Hero widget as a work around.

I'll suggest to simply make the picture a solid color during the animation then.

**Comment by micahmo** [comment] 2023-09-14 17:57
Fixed by #689.

**Closed** 2023-09-22 03:00 UTC
Labels: bug, fixed in upcoming release
