### ISSUE TITLE
Login on lemmy.world is bugged

### ISSUE THREAD

**Issue by HeWhoDead** [thunder-app/thunder#542] opened 2023-08-03 10:37 UTC
**Description**  
When trying to login on lemmy.world it says LemmyAPIexception and doesn't login as it should.

**How to Reproduce**  
1. Go to 'manage accounts'
2. Click on 'add account'

**Expected Behavior**  
Successful login or If account details are false then lot login. 

**Screenshots**  
![IMG_20230803_162812](https://github.com/thunder-app/thunder/assets/49730403/09f47985-1bea-4750-8ad9-646ec63c75bd)

**Device & App Version:**  
 - Device: [e.g. Redmi Note 6 Pro]
 - OS: [e.g. Android 9]
 - Version [e.g. 0.2.1]

**Additional Context**

**Comment by CTalvio** [comment] 2023-08-03 11:48
Is your login correct? Does it work in other apps?

That error is saying your username or password is incorrect.

**Comment by wadamT** [comment] 2023-08-03 17:53
Clearing data of the Thunder app works for me in this case.

**Comment by hjiangsu** [comment] 2023-08-08 04:04
I'll close this since it seems like theres a solution to this issue! Do let me know if the issue is still occurring so that I can open it back up

**Closed by hjiangsu** 2023-08-08 04:04 UTC
Labels: bug, question
