### ISSUE TITLE
Option to show user profile pictures in post view

### ISSUE THREAD

**Issue by Fxsch** [thunder-app/thunder#1221] opened 2024-03-21 11:01 UTC
### Feature Description

There's already the option to show the community profile picture on posts in your feed but when I click on a post, I would like to be able to see the profile pictures of the post author and the commenters.

**Comment by iparks99** [comment] 2024-04-12 17:33
Great idea, I'll start working on this!

**Comment by glyph-se** [comment] 2024-04-18 18:36
Is this a duplicate of https://github.com/thunder-app/thunder/issues/600 ?

**Closed** 2024-05-30 16:11 UTC
Labels: enhancement, fixed in upcoming release
