### ISSUE TITLE
"deleted by creator" replies cannot be dismissed

### ISSUE THREAD

**Issue by pescepalla** [thunder-app/thunder#759] opened 2023-09-21 22:23 UTC
**Description**  
When someone replies your comment and subsequently delete their message, the notification cannot be dismissed and it stays permanently on.

**How to Reproduce**  
1. Post something on Lemmy
2. Have someone reply your message then delete it
3. Check inbox, there's a message saying "deleted by creator" that cannot be dismissed

**Expected Behavior**  
All messages in inbox should be dismissible

**Screenshots**  
![Screenshot_20230922-002206_Thunder](https://github.com/thunder-app/thunder/assets/46329185/1a01f3cc-714e-418e-929a-ef3891aeb16c)

**Device & App Version:**  
 - Device: Fairphone 4
 - OS: iodéos
 - Version 0.23.16 from F-Droid

**Comment by micahmo** [comment] 2023-09-22 02:24
Hey @pescepalla! I believe this issue is a duplicate of #702, #683, and #584. It should have been fixed in #693 and released in [v0.2.4](https://github.com/thunder-app/thunder/releases/tag/0.2.4). If you get a chance, could you try the latest release and report back? Thanks!

**Comment by pescepalla** [comment] 2023-09-22 04:45
It is solved for me!

**Closed** 2023-09-22 04:45 UTC
Labels: bug, duplicate
