### ISSUE TITLE
'Create post' locale and text selector issues

### ISSUE THREAD

**Issue by Baerbeisser** [thunder-app/thunder#1024] opened 2024-01-07 13:22 UTC
**Description**  
In the 'create post' feature (this is new?):

**Requisites**
system being set to left-to-right (european locale)
 
**How to Reproduce** 
Steps to reproduce the behavior (case 1):
1. Type something in Title/URL (behaves corretly)
2. press [space] on keyboard, cursor switches to top left but goes back as you type further
3. unselect field, select it again, you can only type from top left

Steps to reproduce the behavior (case 2):
1. long-press text in Title/URL field and popup copy/cut/paste text is in, i don't know, hebraic?

Steps to reproduce the behavior (case 3):
1. "Mark as NSFW" switch is flipped 180° vertically

**Expected Behavior**  
Feature follows system locale setting 

**Device & App Version:**  
 - Device: OnePlus 9
 - OS: LineageOS 20/Android 13
 - App Version 0.2.7

**Comment by hjiangsu** [comment] 2024-01-08 16:35
Thanks for the issue report! Could I get you to verify a couple pieces of information?

- What language/locale is your system set to?
- What language is Thunder set to? You can see this by going to Settings -> General -> App Language

Could I get you to set Thunder's app language setting to English and let me know if the issues still show up (if it already shows English, set the language to another language, and set it back to English)

Related: https://github.com/thunder-app/thunder/issues/929

**Comment by hjiangsu** [comment] 2024-01-08 17:23
@micahmo Are you able to reproduce this on your end? It might be an Android specific issue as I can't reproduce this!

**Comment by micahmo** [comment] 2024-01-09 02:26
Hmm I can't reproduce either! This is a weird one! @Baerbeisser In addition to @hjiangsu's questions, a screen recording of this issue would also be helpful!

**Comment by Baerbeisser** [comment] 2024-01-09 16:10
Found it. The app language was *somehow* set to (what, arabic? some glyphes).
Guess the weird behavior was some bugging before a restart, after that, everything was right-aligned.
Setting it to english fixed it.
Sorry for the wasted effort.

**Comment by hjiangsu** [comment] 2024-01-09 16:24
Thanks for trying it out! I have a slight idea of what may be causing this.

By default, Thunder will try to get your system's locale/language, and set the appropriate language on the app if there are translations for it. What might be happening here is that Thunder was not able to determine your system's locale, which caused it to default to the first entry in the language selection (in this case, it's Arabic).

Maybe what we can do here to fix this is to have Thunder fallback to English if it is unable to retrieve the system's locale.

**Comment by Baerbeisser** [comment] 2024-01-09 19:53
My locale is Swiss German and i think it was english already the first time i openened the app.
But at the time this happened, the app was already used a few times and set up, language manually set to english too.
I do think it happened because i fiddled with the language setting in the 'Create Post' frame, the timing matches. And it somehow set the language for the whole app upon failing to send the post.
Is that possible?

**Comment by hjiangsu** [comment] 2024-01-11 17:49
> Is that possible?

I don't believe that should be possible, since the language setting in the "Create Post" page is only used to as a way to determine what language your post is in (for Lemmy), and it shouldn't affect anything else within the app.

**Comment by hjiangsu** [comment] 2024-01-17 02:13
I believe this should be fixed in 0.2.8. Could you let me know if you can reproduce the issue? Thanks!

**Closed** 2024-01-17 02:13 UTC
Labels: bug
