### ISSUE TITLE
"Null check operator used on null value" when commenting on a post

### ISSUE THREAD

**Issue by sukhmel** [thunder-app/thunder#1474] opened 2024-07-04 08:25 UTC
### Bug Description

There are two reply buttons in the post, one just under the post works correctly, other is down at the bottom of the screen and it seems to lose context causing "Null check operator used on null value" error. Using it for commenting doesn't work anymore 

### Expected Behaviour

When I click on the bottom reply button I can then post a comment.

### Steps to Reproduce

1. Open a post
2. Press bottom reply button
3. Observe no post preview above the comment text area
4. Try to publish the comment

### Additional Context

This seems to be a rare issue, but it consistently reproduces for me in this post:
https://programming.dev/post/16349241

### App Version

0.5.0-2

### Device

Pixel 8 Pro 

### OS

Android 14

**Comment by hjiangsu** [comment] 2024-07-08 21:16
> Observe no post preview above the comment text area

Hmm, I'm unable to reproduce this issue here. In both cases, I can still see the post preview. Does this happen on a specific user/instance? I can try to reproduce it using a different instance (tested this on lemmy.world instance)

https://github.com/thunder-app/thunder/assets/30667958/a240fc30-f79e-4819-a8ea-64fd57d567d4

**Comment by sukhmel** [comment] 2024-07-09 00:27
Doesn't reproduce for me anymore, either. Maybe some rare bug or a cache issue ¯\\\_(ツ)\_/¯

I will post again if that happens again, and will maybe try with different instances that time

**Comment by hjiangsu** [comment] 2024-07-10 16:31
Sounds good! I'll just close this issue but feel free to let me know if you encounter this again.

**Closed by hjiangsu** 2024-07-10 16:31 UTC
Labels: bug
