### ISSUE TITLE
Account keeps getting logged out

### ISSUE THREAD

**Issue by shreya-shah** [thunder-app/thunder#493] opened 2023-07-27 18:01 UTC
**Description**  
Once logging into my account, it works as usual. But after the app is removed from my recent apps and when I open it back my account is not logged in anymore. So I have to add it back again. This keeps happening repeatedly.

**How to Reproduce**  
1. On a fresh install, log into an account.
2. Clear the app from the recent apps section
3. On opening the app again, the logged in account and subscriptions are not there anymore.

**Expected Behavior**  

**Screenshots**  
![Screenshot_20230727_233125](https://github.com/thunder-app/thunder/assets/27025403/94c1c621-11cc-4fff-90c6-b236b6e1597d)

**Device & App Version:**  
 - Device: Samsung s23 ultra
 - OS: Android 13
 - Version : v0.2.1+13

**Comment by hjiangsu** [comment] 2023-07-30 01:21
I'm unable to reproduce this unfortunately. Do you have any more info you can provide to help?

For example:
- When you tap on manage accounts, do you see any accounts there or is it empty?
- What instance are you logging into?

Thanks!

**Comment by shreya-shah** [comment] 2023-07-30 03:31
When I tap on manage accounts, there are no accounts shown.
 I was logging into lemmy.world.


I will try again with a fresh install.

**Comment by shreya-shah** [comment] 2023-07-30 08:01
I think this a slightly different issue. I am logged in, because if I post a caomment from the floating button I am able to do with the instance I am logged in with, but 

1. the comment and post actions (on the bar below) don't work. The post actions are disabled and comment actions are not visible at all.(Attaching screenshot) 
![Screenshot_20230730_132616](https://github.com/thunder-app/thunder/assets/27025403/01487f1a-6d11-419f-a21e-4ee0e8243e92)

Also attaching screenshot of when I again logged in, but didnt remove the app from my recent apps, to show the difference

![Screenshot_20230730_132919](https://github.com/thunder-app/thunder/assets/27025403/13aa3bf8-ff04-4f6c-b2fd-83e81d9c3619)


2. Can't see my account under manage accounts
3. Can't see subscriptions in the side menu bar.

**Comment by tasmo** [comment] 2023-07-30 11:08
Have the same problem as described before.

**Comment by hjiangsu** [comment] 2023-07-30 16:08
That is weird behaviour. It doesn't seem like an instance thing since I'm also on lemmy.world. It could be an android specific issue.

If you don't mind, could you go into the debug setting's menu and clear local database and preferences and try again? No need to do a clean install!

I might pull in @ajsosa or @micahmo to see if they can reproduce this issue

**Comment by shreya-shah** [comment] 2023-07-30 18:31
Clearing local database and preferences seems to help.
I am seeing post and comment actions now, and my notifications as well.
But still not able to see my subscriptions.
![Screenshot_20230730_235821](https://github.com/thunder-app/thunder/assets/27025403/a660cca0-8fff-41fe-9180-c5a128812bcd)

**Comment by micahmo** [comment] 2023-07-31 02:28
I haven't seen this issue on Android, but then again I'm logging in and out so much to test, I might've missed it. Sounds like some good results from clearing the local storage though!

**Comment by shreya-shah** [comment] 2023-07-31 04:39
Yes, clearing local storage seems to fix it. Thanks.

**Comment by hjiangsu** [comment] 2023-08-03 21:30
Closing issue since it seems like its been fixed!

**Closed by hjiangsu** 2023-08-03 21:30 UTC
Labels: bug
