### ISSUE TITLE
Numbers overlap when name is long

### ISSUE THREAD

**Issue by Varven2** [thunder-app/thunder#1403] opened 2024-05-31 03:48 UTC
### Bug Description

![Screenshot_2024-05-31-13-41-51-42_ab870a90287380db09018f87a3131b61](https://github.com/thunder-app/thunder/assets/171309970/be0c243a-9ca7-4820-8d44-e7b02e1f8a4f)

### Expected Behaviour

The numbers are not suppose to overlap 

### Steps to Reproduce

Find a post go into the comments and look for someone with a long name

### App Version

0.4.0

### Device

Oppo a96

### OS

Android 13

**Comment by hjiangsu** [comment] 2024-05-31 03:52
Thanks for the report! I believe this is a duplicate of #976

**Comment by Varven2** [comment] 2024-05-31 03:57
Yer it is my b

**Closed** 2024-05-31 03:58 UTC
Labels: bug
