### ISSUE TITLE
Editing a comment from your profile comment history results in the error: "Error: Could  not determine post to comment to."

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1055] opened 2024-01-14 22:27 UTC
**Description**  
If you edit one of your posts from the profile tab, it results in the following error:
```
Error: Could not determine post to comment to.
```
and then fails to apply the edit.

**How to Reproduce**  
1. Go to your profile tab.
2. Go to comments
3. Pick a comment from the list, and tap edit
4. Try to apply an edit
5. Observe the error "Error: Could not determine post to comment to." popping up at the bottom

**Expected Behavior**  
I would expect to be able to edit a comment from my user profile.

**Screenshots**  
![Screenshot_20240114-142011](https://github.com/thunder-app/thunder/assets/7829231/813f1541-7676-4903-949d-0ecc9d3e4348)

**Device & App Version:**  
 - Device: Google Pixel 6
 - OS: Android 14
 - App Version: v0.2.8

**Additional Context**  
This can be worked around by fully opening the comment in the post, and then editing it from there rather than from your profile comment history.

**Comment by hjiangsu** [comment] 2024-01-15 21:41
This is a duplicate of https://github.com/thunder-app/thunder/issues/738 - I haven't gotten to this yet since its a bigger refactor as mentioned in the other issue. I'll close this in favour of the other issue!

**Closed by hjiangsu** 2024-01-15 21:41 UTC
Labels: bug
