### ISSUE TITLE
Share links to Thunder to create new post

### ISSUE THREAD

**Issue by Grafcube** [thunder-app/thunder#639] opened 2023-08-15 04:15 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes when I have a link to a lemmy instance, it would be convenient if I could open it in the app using either Android's supported URLs feature or by sharing the link.

**Describe the solution you'd like**
I would like a way to use Thunder as the default app to open lemmy/kbin links. In case the instance is not in the list of supported URLs (IIRC only a fixed list of supported URLs can be added), I could share the URL to the app and then choose between creating a new post with that URL or opening it in the app with my preferred account.

**Describe alternatives you've considered**
I don't know if any other method would work.

**Additional context**
None

**Comment by realmain** [comment] 2023-08-21 21:12
Duplicate of #60

**Comment by micahmo** [comment] 2023-08-22 02:51
I'm going to close this as a dup in favor of #60, only because that one's older and has more discussion and votes. However, @Grafcube feel free to reopen this, or add any other specific discussion points as needed!

**Comment by micahmo** [comment] 2023-10-17 20:12
I realized there's a suggestion in this issue that isn't captured elsewhere, so I'm going to rename and reopen to track this idea in particular:

> I could share the URL to the app and then choose between creating a new post with that URL

**Closed** 2023-11-15 19:45 UTC
Labels: enhancement, fixed in upcoming release
