### ISSUE TITLE
[Feature Request] Go back from a community instead of exit

### ISSUE THREAD

**Issue by avasts** [thunder-app/thunder#180] opened 2023-07-02 14:42 UTC
The behavior on Android as of right now is: From the main feed, click on a community from the subscribed communities, and click on a post. From the post/comments view, swiping once to go back will take you back to the community page. Swiping again will exit the app instead of taking you back to your main feed. I think the user experience would be much better if the back from communities went back to the main feed instead of exiting.

Adding this would make a more cohesive experience, as right now the back button/gesture does two completely different actions depending on where you are in the app.

**Comment by hjiangsu** [comment] 2023-07-02 15:25
Hmm, I'll have to think about this. The reason why you're experiencing this is because the community feed that you see when you tap on a community from the sidebar shares the same view as the All/Local/Subscribed feeds

If you notice, tapping on a specific community from a post or from the search view will create a new "view", which then will allow you to use the back button to return back to where you previously were.

I do want to get further feedback on how this should be done by the community! If it makes more sense to make tapping on a community from the sidebar a new "view", then I can definitely add that in :D

**Comment by coslu** [comment] 2023-07-02 16:09
I think it makes more sense. I think it also makes sense for the back button/gesture to go back to the main feed from other screens like settings or accounts before exiting the app.

**Comment by machinaeZER0** [comment] 2023-07-02 19:19
I agree that this would be a positive change if possible to implement in the future! Not totally dissimilar to the ideas around the Home button in #149 - that might also require the "view" creation you're speaking about, @hjiangsu

**Comment by micahmo** [comment] 2023-08-28 04:39
If I'm reading this correctly, I believe it's a duplicate of #375 which was fixed in #402. Do others agree?

**Comment by machinaeZER0** [comment] 2023-08-28 11:22
I think that's right!

**Closed** 2023-08-28 13:14 UTC
Labels: enhancement
