### ISSUE TITLE
Post image size change when using comment floating button 

### ISSUE THREAD

**Issue by fedikhatib** [thunder-app/thunder#906] opened 2023-11-22 16:35 UTC
**Description**  
In a post détails with image when navigating with the comment flaot button the image size is changing.

**How to Reproduce**  
1. Go to a post 
2. Tap on floating comment button  up and down 
4. The post image size change

**Expected Behavior**  
The image size and resolution not changing 

**Screenshots**  

https://github.com/thunder-app/thunder/assets/34138112/2f9ff272-c49e-44ca-aee2-d59c55562442

**Device & App Version:**  
 - Device: Redmi note 11 pro 
 - OS: Android 13
 - App Version 0.2.5

**Comment by micahmo** [comment] 2023-11-22 16:42
Any chance this is a dup of or related to #705? I think this is the same visual issue where things occasionally get stretched.

**Comment by hjiangsu** [comment] 2024-05-31 03:18
I'll close this as it seems like it's a duplicate of #705

**Closed by hjiangsu** 2024-05-31 03:18 UTC
Labels: bug
