### ISSUE TITLE
System buttons are white on white and barely visible on both themes

### ISSUE THREAD

**Issue by Porkepix** [thunder-app/thunder#1224] opened 2024-03-22 08:48 UTC
### Bug Description

Both themes have a white on white system bar & buttons making it barely visible.

### Expected Behaviour

Color of the buttons should be fixed for light theme.
Dark theme shouldn'd have white background and have the buttons adjusted accordingly

### Steps to Reproduce

Run Thunder-app on the same version of Android

### Additional Context

<details>
<summary>
Screenshots
</summary>

![Screenshot_20240322-092019](https://github.com/thunder-app/thunder/assets/709500/44a6d424-2f1c-4081-9e5b-821008a3199c)
![Screenshot_20240322-092034](https://github.com/thunder-app/thunder/assets/709500/f6c1b549-e647-47c9-9107-24111acb1f0f)

</details>

### App Version

0.2.9

### Device

Xperia XZ

### OS

Android Oreo (8.0)

**Comment by micahmo** [comment] 2024-03-22 13:19
Possibly the same issue as #372?

**Comment by hjiangsu** [comment] 2024-03-30 18:25
Considering this a duplicate of #372 so I'll close this one in favour of the other one.

**Closed by hjiangsu** 2024-03-30 18:25 UTC
Labels: bug
