### ISSUE TITLE
Hide bottom navigation bar on scroll

### ISSUE THREAD

**Issue by IAmCaligvla** [thunder-app/thunder#1175] opened 2024-03-08 03:02 UTC
### Feature Description

An option for hiding the bottom navigation bar while scrolling through posts and comments, like the `hide top bar on scroll` option.

**Comment by micahmo** [comment] 2024-03-08 13:26
Related to / dup of #74.

**Comment by hjiangsu** [comment] 2024-03-08 17:00
I'll close this since this is a duplicate of #74

**Closed by hjiangsu** 2024-03-08 17:00 UTC
Labels: enhancement
