### ISSUE TITLE
"Show Full Height Images" Option squishes images

### ISSUE THREAD

**Issue by x4740N** [thunder-app/thunder#1448] opened 2024-06-14 14:02 UTC
### Bug Description

As seen below in the attached images thunder for lemmy squishes the full height images when this option is enabled

![Screenshot_20240614-235335_Thunder](https://github.com/thunder-app/thunder/assets/17174184/9c90f721-a886-47a1-88ae-04ede9d8c94f)

![Screenshot_20240614-235343_Thunder](https://github.com/thunder-app/thunder/assets/17174184/4485e0d2-9c9f-4d5a-8529-986aa7f2f0a7)

### Expected Behaviour

I expect the app to show images at full height and not squish them

### Steps to Reproduce

1. Enable "Show Full Height Images" option 
2.  View any post on lemmy through the app that contains an image

### App Version

v0.5.0-1

### Device

Samsung Galaxy A70

### OS

Android 11

**Comment by kratoz29** [comment] 2024-06-14 21:54
I was not aware this was a bug, I thought this was the way the app handled it 😂

I even played around with the settings but no luck, glad to see it is a bug.

**Comment by njosey** [comment] 2024-06-14 23:20
> I was not aware this was a bug, I thought this was the way the app handled it 😂
> 
> I even played around with the settings but no luck, glad to see it is a bug.

I hope its a bug, I'm 90% sure it is since that doesn't look like that is the intended function of the option 

It's very annoying to have to open up each image especially when I want to browse a image heavy lemmy community

**Comment by njosey** [comment] 2024-06-17 17:07
Hello.....

Anyone going to look at this

**Comment by hjiangsu** [comment] 2024-06-17 18:24
Hey, thanks for the report! Sorry it took a bit longer to get to this one. Just a few questions:
- Does this happen to all images within the feed when you have that option on? Or does it just affect some images?
- Are you connected to wifi or cellular (or both) when this happens?

For some additional context into why this issue occurs:
- Lemmy's API doesn't pass back the image's height/width information when we fetch the posts. We need this height/width information in order to determine the proper amount of "space" to allocate to the image in the feed (otherwise, scrolling through the feed makes everything jump around which is not ideal).
- In order to work around this, we calculate each image's width/height after we get the post information. Before we do this though, we need to fetch the image itself which can sometimes take a long time (depending on the size of the image, the network, etc.). As a safe guard, we place a maximum timeout for how long we allow the image fetching to take place. If it takes too long to fetch the image, we set a default dimension size for the image (which is why you might encounter the squished images).

The good news here is that it looks like Lemmy will be adding image width/height information in a future version which should essentially fix this issue since we no longer need to fetch the image and do those calculations!

However, before that happens, the only thing we can really do is increase the amount of time allowed for the image to download. This does have a negative effect where loading the initial feed may take longer if certain images take a long time to be fetched.

I hope this makes sense and feel free to ask any follow up questions!

**Comment by njosey** [comment] 2024-06-18 17:31
@hjiangsu 

> Does this happen to all images within the feed when you have that option on? Or does it just affect some images?

This does happen with all images

> Are you connected to wifi or cellular (or both) when this happens?

I am only connected to WiFi

> However, before that happens, the only thing we can really do is increase the amount of time allowed for the image to download.

Just a suggestion but what about about adding that as a user settable value for that as an advanced feature for more advanced users of the app if that already isn't an option

**Comment by hjiangsu** [comment] 2024-06-18 23:57
> This does happen with all images

Interesting - this is a bug then as it should at least be able to retrieve most of the dimensions within the given timeout

> Just a suggestion but what about about adding that as a user settable value for that as an advanced feature for more advanced users of the app if that already isn't an option

I can add this in as part of a debug setting for the next nightly to see if increasing the timeout value will help resolve this issue! I'm hesitant to add this in as a main setting because thumbnail metadata will eventually be included in Lemmy's API (which will most likely render this setting useless)

**Comment by hjiangsu** [comment] 2024-06-21 17:25
Just an update on this - I'm adding in a new setting in the Debug section to change the timeout value for fetching image dimensions! This should hopefully reduce the issues you're facing with images being squished.

Once this is out in a nightly build, please let me know if increasing the timeout value fixes the issues!

**Comment by njosey** [comment] 2024-07-08 18:25
The option didn't help, I have it on the max 10 seconds and nothing happens

The images are still squished

**Comment by hjiangsu** [comment] 2024-07-08 18:37
Thanks for the update, and sorry to hear that the setting didn't fix anything. Could I possibly get more details to see if I can reproduce this myself?

You mentioned that you're connected to Wifi when this occurs.
- Do you also have a VPN enabled when connected to Wifi? This _shouldn't_ matter, but it might be useful to help reproduce the issue
- What is your home instance, or the instance that you're seeing these issues?
- Could you also provide the Lemmy version that your home instance is in?

**Comment by njosey** [comment] 2024-08-09 03:17
Sorry about not responding for a while, I meant to respond to this but got busy and forgot

> Do you also have a VPN enabled when connected to Wifi? This shouldn't matter, but it might be useful to help reproduce the issue

No I do not use a VPN

> What is your home instance, or the instance that you're seeing these issues?

lemm.ee 

> Could you also provide the Lemmy version that your home instance is in?

BE: 0.19.5

> Additionally, when you increase the timeout value, do you notice a large difference in the initial loading times in the feed?

No, it is 2-3 seconds When I increase the timeout value and does not change

**Comment by pfaca** [comment] 2024-08-12 00:05
I have the same problem using the lemm.ee instance. If I use another instance it works has intended.
But using full height images in voyager and in eternity, lemm.ee works without problems.

**Comment by hjiangsu** [comment] 2024-08-12 16:54
Thanks for the responses! I believe I narrowed it down now. It seems like lemm.ee is using image proxying to handle images, which Thunder was not handling properly.

I'll push out a fix for this in the next general release!

**Comment by hjiangsu** [comment] 2024-08-12 20:00
Just an update - I've pushed out a new nightly build (v0.5.0-6) which should address this issue. Please let me know if this fixes the problem!

**Comment by pfaca** [comment] 2024-08-12 21:52
V0.5.0-6 fixed it for me.

Thanks for the fix and your work @hjiangsu .

**Comment by x4740N** [comment] 2024-08-13 15:15
V0.5-6 has fixed the issue for me

**Closed** 2024-08-15 21:15 UTC
Labels: bug, fixed in upcoming release

**Comment by RandomDennisLee** [comment] 2024-11-30 23:56
Similar issue occurring on 0.6.0-1, reported in #1617
