### ISSUE TITLE
Can't update to v0.3.0 on F-Droid due to certificate error.

### ISSUE THREAD

**Issue by K4LCIFER** [thunder-app/thunder#1296] opened 2024-04-11 02:05 UTC
### Bug Description

When trying to update Thunder on F-rdoid, it gives the following error:
![share_3139496590697703156](https://github.com/thunder-app/thunder/assets/7829231/bdc53e79-f479-48c2-9dbe-d6ddfb687385)

### Expected Behaviour

I would expect to be able to update the app.

### Steps to Reproduce

1. Have thunder installed through F-Droid
2. Try to update to v0.3.0 
3. Observe that you get the certificate error

### Additional Context

The F-Droid app that I use is [Droid-ify](https://github.com/Droid-ify/client)

### App Version

0.2.9

### Device

Pixel 6

### OS

Android 14

**Comment by hjiangsu** [comment] 2024-04-11 15:53
Hmm, thats interesting. I don't believe I changed much in the build process. I can try to reproduce this on an emulator, but can't guarantee if I'll be able to do so.

Update - I tried to follow these steps on an emulator but was unable to reproduce the issue:
- Installed v0.2.9 from GitHub
- Installed Droid-ify
- Updated Thunder to v0.3.0 through Droid-ify

I don't think there's a way to install v0.2.9 via Droid-ify because that version was replaced by v0.3.0. If you have any other steps or ideas, please let me know!

**Comment by K4LCIFER** [comment] 2024-05-14 05:45
I've found that I can trigger the error if I tap the version at the bottom of the application page in Droid-ify.
![share_6604493226740705846](https://github.com/thunder-app/thunder/assets/7829231/4aae3082-6cc5-4819-99b6-f2de665af173)
This may be a bug with Droid-ify — I'm not entirely sure.

**Comment by hjiangsu** [comment] 2024-05-31 02:33
I'm still unable to reproduce this. Can you check if this issue is still present on v0.4.0? Thanks!

**Comment by K4LCIFER** [comment] 2024-05-31 20:42
> Can you check if this issue is still present on v0.4.0?

![Screenshot_20240531-134046.png](https://github.com/thunder-app/thunder/assets/7829231/254a0381-861b-45a5-a9aa-cc7e31a3b80e)

Unfortunately, it is. One note is that I'm on a beta version of Android — could this be having an effect on the certificates?

**Comment by hjiangsu** [comment] 2024-05-31 22:11
Hmm, interesting. These are the steps I tried to reproduce this issue (without any success):
- Started on a clean emulator
- Downloaded Droid-ify from their GitHub page
- Downloaded an older Thunder version from GitHub releases (v0.3.0)
- Attempted to update to v0.4.0 via Droid-ify to latest version

When doing this, it allowed me to install the update without any errors. How did you initially download Thunder? Was it through Droid-ify or some other means?

Could you also confirm the current version of Thunder you're on? Thanks!

**Comment by K4LCIFER** [comment] 2024-06-04 22:37
> How did you initially download Thunder? Was it through Droid-ify or some other means?

Unfortunately, I can't remember.

> Could you also confirm the current version of Thunder you're on?

I'm now on 0.4.0, but, previously, I was on 0.3.x (I can't exactly recall the exact version, but I'm quite certain it was the version directly before 0.4.0)

The way that I managed to install 0.4.0 was I uninstalled Thunder, and just reinstalled the 0.4.0 version from Droid-ify. I'll see if it'll let me update through Droid-ify when the next Thunder update rolls out.

**Comment by hjiangsu** [comment] 2024-06-05 00:56
Sounds good! Do keep me updated if this issue occurs in the future, as it could potentially affect a lot of other users.

**Comment by hjiangsu** [comment] 2024-08-15 21:21
@K4LCIFER Have you experienced this issue when updating to v0.5.0? If not, then I'll go ahead and close this issue. Otherwise, we might need to do further investigation to figure out the root cause.

**Comment by K4LCIFER** [comment] 2024-08-15 21:30
Nope! I was able to update smoothly. Thank you for checking in/keeping up with this issue ☺️

**Comment by hjiangsu** [comment] 2024-08-15 21:41
No problem! I'm glad the issue is resolved. I'll go ahead and close this now.

**Closed by hjiangsu** 2024-08-15 21:41 UTC
Labels: bug, on-hold
